

DROP TABLE IF EXISTS WEB_USER CASCADE;
CREATE TABLE WEB_USER (
	ID SERIAL PRIMARY KEY,
	USERNAME TEXT NOT NULL UNIQUE,
	PASSWORD TEXT NOT NULL,
	EMAIL TEXT UNIQUE NOT NULL,
	ROLE TEXT
);

DROP TABLE IF EXISTS MEMBER CASCADE;
CREATE TABLE MEMBER (
	ID SERIAL PRIMARY KEY,
	NAME TEXT NOT NULL,
	USER_ID INT REFERENCES WEB_USER(ID)
);

DROP TABLE IF EXISTS ARTICLE CASCADE;
CREATE TABLE ARTICLE (
	ID SERIAL PRIMARY KEY,
	TITLE TEXT,
	CONTENT TEXT,
	IMAGE TEXT,
	TAG TEXT
);

DROP TABLE IF EXISTS ARTICLE_COMMENT CASCADE;
CREATE TABLE ARTICLE_COMMENT (
	ID SERIAL PRIMARY KEY,
	USER_ID INT REFERENCES WEB_USER(ID),
	ARTICLE_ID INT REFERENCES ARTICLE(ID),
	CONTENT TEXT
);

INSERT INTO WEB_USER (USERNAME, PASSWORD, EMAIL, ROLE) VALUES ('admin', '123', 'admin@gmail.com' ,'role_admin');
INSERT INTO WEB_USER (USERNAME, PASSWORD, EMAIL, ROLE) VALUES ('ndnhuy', '123', 'ndnhuy2504@gmail.com', 'role_user');
INSERT INTO WEB_USER (USERNAME, PASSWORD, EMAIL, ROLE) VALUES ('dtbthuy', '123', 'dtbthuy@gmail.com', 'role_user');
INSERT INTO WEB_USER (USERNAME, PASSWORD, EMAIL, ROLE) VALUES ('pthuy', '123', 'pthuy@gmail.com', 'role_user');

INSERT INTO MEMBER (NAME, USER_ID) VALUES ('Nguyen Dat Nhat Huy', 2);
INSERT INTO MEMBER (NAME, USER_ID) VALUES ('Doan Thi Bich Thuy', 3);
INSERT INTO MEMBER (NAME, USER_ID) VALUES ('Pham Thanh Huy', 4);

INSERT INTO ARTICLE (TITLE, CONTENT, IMAGE, TAG) VALUES ('Title 1', 'Content Of Article 1', null, 'news');
INSERT INTO ARTICLE (TITLE, CONTENT, IMAGE, TAG) VALUES ('Title 2', 'Content Of Article 2', null, 'others');
INSERT INTO ARTICLE (TITLE, CONTENT, IMAGE, TAG) VALUES ('Title 3', 'Content Of Article 3', null, 'event');

INSERT INTO ARTICLE_COMMENT (USER_ID, ARTICLE_ID, CONTENT) VALUES (2, 1, 'Hay qua');
INSERT INTO ARTICLE_COMMENT (USER_ID, ARTICLE_ID, CONTENT) VALUES (3, 1, 'Good job!');
INSERT INTO ARTICLE_COMMENT (USER_ID, ARTICLE_ID, CONTENT) VALUES (4, 1, 'Nice!');
INSERT INTO ARTICLE_COMMENT (USER_ID, ARTICLE_ID, CONTENT) VALUES (2, 2, 'Suck');

